//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FileBrowser.rc
//
#define IDD_ABOUTBOX				100
#define IDR_POPUP_EDIT				119
#define ID_STATUSBAR_PANE1			120
#define ID_STATUSBAR_PANE2			121
#define IDS_STATUS_PANE1			122
#define IDS_STATUS_PANE2			123
#define IDS_TOOLBAR_STANDARD		124
#define IDS_TOOLBAR_CUSTOMIZE		125
#define ID_VIEW_CUSTOMIZE			126
#define IDR_MAINFRAME				128
#define IDR_MAINFRAME_256			129
#define IDR_FILE_BROWSER_DOC_TYPE				130
#define ID_WINDOW_MANAGER			131
#define ID_QUICK_ACCESS_VIEW			533
#define ID_FILE_LIST_VIEW			534
#define ID_PROPERTIES				135
#define ID_OPEN						136
#define ID_OPEN_WITH				137
#define ID_DUMMY_COMPILE			138
#define ID_CLASS_ADD_MEMBER_FUNCTION	139
#define ID_CLASS_ADD_MEMBER_VARIABLE	140
#define ID_CLASS_DEFINITION			141
#define ID_CLASS_PROPERTIES			142
#define ID_COMPARE_FOLDERS				143
#define ID_SORT_MENU				144
#define ID_SORTING_BY_FILE_SIZE_ASC		145
#define ID_SORTING_BY_NAME_ASC	146
#define ID_SORTING_BY_FILE_TYPE_ASC		147
#define ID_SORTING_BY_FILE_ACCESS_ASC		148
#define IDS_QUICK_ACCESS_VIEW				155
#define IDS_FILE_LIST_VIEW				156
#define IDI_FILE_VIEW				161
#define IDI_FILE_VIEW_HC			162
#define IDI_CLASS_VIEW				163
#define IDI_CLASS_VIEW_HC			164
#define IDR_EXPLORER				169
#define IDB_EXPLORER_24				170
#define IDR_SORT					171
#define IDB_SORT_24					172
#define IDR_POPUP_SORT				173
#define IDR_POPUP_EXPLORER			174
#define IDB_DIRECTORY_TREE_VIEW				175
#define IDB_DIRECTORY_TREE_VIEW_24			176
#define IDB_FILELIST_VIEW				177
#define IDB_FILELIST_VIEW_24			178
#define IDR_MENU_IMAGES				179
#define IDB_MENU_IMAGES_24			180
#define ID_TOOLS_MACRO				181
#define IDS_EXPLORER				305
#define IDS_EDIT_MENU				306
#define IDB_LARGEICONS              307
#define IDB_SMALLICONS              308
#define ID_SHOW_LIST_DETAILS				309
#define ID_SHOW_LIST_LIST				310
#define ID_SHOW_LIST_SMALLICON              311
#define ID_SHOW_LIST_ICON			312

#define ID_SORTING_BY_FILE_SIZE_DESC		313
#define ID_SORTING_BY_NAME_DESC				314
#define ID_SORTING_BY_FILE_TYPE_DESC		315
#define ID_SORTING_BY_FILE_ACCESS_DESC		316

#define ID_WINDOW_MANAGER1			317
#define ID_WINDOW_TILE_HORZ1		318
#define ID_TOOLS_MACRO1				319
#define ID_WINDOW_CASCADE1			320
#define IDS_TARGET_QUICK_ACCESS_VIEW				321
#define ID_TARGET_QUICK_ACCESS_VIEW			322
#define IDS_TARGET_FILE_LIST_VIEW				323
#define ID_TARGET_FILE_LIST_VIEW			324

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE	400
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		400
#define _APS_NEXT_COMMAND_VALUE		32771
#endif
#endif
